# Generated by Django 4.2.1 on 2023-06-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='count',
            new_name='product_count',
        ),
    ]
